// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using uberworks_webapi.Data;

#nullable disable

namespace uberworks_webapi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805171850_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("uberworks_webapi.Models.Entities.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_CHAT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("CL_CLIENT_ID");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CL_MESSAGE");

                    b.Property<DateTime>("MessageDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CL_MESSAGE_DATE")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ProfessionalId")
                        .HasColumnType("int")
                        .HasColumnName("PK_PROFESSIONAL_ID");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("TBL_CHATS", (string)null);
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_PAYMENT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("CL_AMOUNT");

                    b.Property<string>("Method")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CL_METHOD");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CL_PAYMENT_DATE")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("PK_SERVICE_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("CL_STATUS");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("TBL_PAYMENTS", null, t =>
                        {
                            t.HasCheckConstraint("CK_PAYMENTS_METHOD", "CL_METHOD IS NULL OR CL_METHOD IN ('CREDITCARD','PAYPAL','ZELLE')");
                        });
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.Penalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_PENALTY_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CL_END_DATE");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CL_REASON");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CL_START_DATE")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CL_TYPE");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("PK_USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TBL_PENALTIES", (string)null);
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.Professional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_PROFESSIONAL_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Availability")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CL_AVAILABILITY");

                    b.Property<decimal>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("CL_AVERAGE_RATING");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CL_DESCRIPTION");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CL_EXPERIENCE");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CL_LOCATION");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("PK_USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TBL_PROFESSIONALS", (string)null);
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_REVIEW_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("CL_CLIENT_ID");

                    b.Property<byte?>("ClientRating")
                        .HasColumnType("tinyint")
                        .HasColumnName("CL_CLIENT_RATING");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CL_COMMENT");

                    b.Property<int>("ProfessionalId")
                        .HasColumnType("int")
                        .HasColumnName("PK_PROFESSIONAL_ID");

                    b.Property<byte?>("ProfessionalRating")
                        .HasColumnType("tinyint")
                        .HasColumnName("CL_PROFESSIONAL_RATING");

                    b.Property<DateTime>("ReviewDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CL_REVIEW_DATE")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("PK_SERVICE_ID");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProfessionalId");

                    b.HasIndex("ServiceId");

                    b.ToTable("TBL_REVIEWS", null, t =>
                        {
                            t.HasCheckConstraint("CK_REVIEWS_RATINGS", "(CL_CLIENT_RATING IS NULL OR CL_CLIENT_RATING BETWEEN 1 AND 5) AND (CL_PROFESSIONAL_RATING IS NULL OR CL_PROFESSIONAL_RATING BETWEEN 1 AND 5)");
                        });
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_REWARD_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CL_LAST_UPDATE_DATE")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("CL_POINTS");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("PK_USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TBL_REWARDS", (string)null);
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_SERVICE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("CL_CLIENT_ID");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CL_DESCRIPTION");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CL_IMAGE_URL");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CL_LOCATION");

                    b.Property<decimal?>("ProposedPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("CL_PROPOSED_PRICE");

                    b.Property<DateTime>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CL_REQUEST_DATE")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("CL_STATUS");

                    b.Property<int>("WorkTypeId")
                        .HasColumnType("int")
                        .HasColumnName("PK_WORK_TYPE_ID");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("WorkTypeId");

                    b.ToTable("TBL_SERVICES", (string)null);
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.ServiceProfessional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_SERVICE_PROFESSIONAL_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("NegotiatedPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("CL_NEGOTIATED_PRICE");

                    b.Property<int>("ProfessionalId")
                        .HasColumnType("int")
                        .HasColumnName("PK_PROFESSIONAL_ID");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("PK_SERVICE_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("UNDER NEGOTIATION")
                        .HasColumnName("CL_STATUS");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalId");

                    b.HasIndex("ServiceId");

                    b.ToTable("TBL_SERVICE_PROFESSIONALS", (string)null);
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_USER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("CL_EMAIL");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CL_FIRST_NAME");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CL_LAST_NAME");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CL_PASSWORD");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CL_PHONE");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CL_REGISTRATION_DATE")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CL_ROLE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("CL_STATUS");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("TBL_USERS", null, t =>
                        {
                            t.HasCheckConstraint("CK_USERS_ROLE", "CL_ROLE IN ('CLIENT','PROFESSIONAL','ADMINISTRATOR','SUPPORT')");
                        });
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.WorkType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_WORK_TYPE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CL_DESCRIPTION");

                    b.Property<string>("Includes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CL_INCLUDES");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CL_NAME");

                    b.Property<string>("NotIncludes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CL_NOT_INCLUDES");

                    b.HasKey("Id");

                    b.ToTable("TBL_WORKTYPES", (string)null);
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.Chat", b =>
                {
                    b.HasOne("uberworks_webapi.Models.Entities.User", "Client")
                        .WithMany("ChatsAsClient")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("uberworks_webapi.Models.Entities.Professional", "Professional")
                        .WithMany("Chats")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.Payment", b =>
                {
                    b.HasOne("uberworks_webapi.Models.Entities.Service", "Service")
                        .WithMany("Payments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.Penalty", b =>
                {
                    b.HasOne("uberworks_webapi.Models.Entities.User", "User")
                        .WithMany("Penalties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.Professional", b =>
                {
                    b.HasOne("uberworks_webapi.Models.Entities.User", "User")
                        .WithOne("Professional")
                        .HasForeignKey("uberworks_webapi.Models.Entities.Professional", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.Review", b =>
                {
                    b.HasOne("uberworks_webapi.Models.Entities.User", "Client")
                        .WithMany("ReviewsWritten")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("uberworks_webapi.Models.Entities.Professional", "Professional")
                        .WithMany("Reviews")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("uberworks_webapi.Models.Entities.Service", "Service")
                        .WithMany("Reviews")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Professional");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.Reward", b =>
                {
                    b.HasOne("uberworks_webapi.Models.Entities.User", "User")
                        .WithOne("Reward")
                        .HasForeignKey("uberworks_webapi.Models.Entities.Reward", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.Service", b =>
                {
                    b.HasOne("uberworks_webapi.Models.Entities.User", "Client")
                        .WithMany("ServicesRequested")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("uberworks_webapi.Models.Entities.WorkType", "WorkType")
                        .WithMany("Services")
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.ServiceProfessional", b =>
                {
                    b.HasOne("uberworks_webapi.Models.Entities.Professional", "Professional")
                        .WithMany("ServiceProfessionals")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("uberworks_webapi.Models.Entities.Service", "Service")
                        .WithMany("ServiceProfessionals")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professional");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.Professional", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Reviews");

                    b.Navigation("ServiceProfessionals");
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.Service", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Reviews");

                    b.Navigation("ServiceProfessionals");
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.User", b =>
                {
                    b.Navigation("ChatsAsClient");

                    b.Navigation("Penalties");

                    b.Navigation("Professional");

                    b.Navigation("ReviewsWritten");

                    b.Navigation("Reward");

                    b.Navigation("ServicesRequested");
                });

            modelBuilder.Entity("uberworks_webapi.Models.Entities.WorkType", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
