// =====================================================================================
// FILE SUMMARY
// What it does: This is a professional's "proposal" on a Service — each professional who
//               bids on the same Service has their own row here, with their own price,
//               estimated arrival minutes, and status (under negotiation / accepted /
//               rejected / in progress / completed). When the client accepts a proposal,
//               this row moves to Accepted and the other proposals on the same Service are
//               automatically rejected (see Services/ServiceProfessionalService.cs →
//               AcceptProposalAsync).
// Entities connected: Professional.cs (N:1), Service.cs (N:1)
// Tables related: TBL_SERVICE_PROFESSIONALS
//                 (mapping in Data/Configurations/ServiceProfessionalConfiguration.cs)
// =====================================================================================
using uberworks_webapi.Common.Enums;

namespace uberworks_webapi.Models.Entities;

/// <summary>
/// Maps to TBL_SERVICE_PROFESSIONALS (N:M relationship between Service and Professional,
/// representing a professional's negotiation/bid on a service).
/// </summary>
public class ServiceProfessional
{
    public int Id { get; set; }
    public int ProfessionalId { get; set; }
    public int ServiceId { get; set; }

    public decimal? NegotiatedPrice { get; set; }

    /// <summary>Minutes the professional declares they'll take to arrive, at proposal time.</summary>
    public int EstimatedArrivalMinutes { get; set; }

    /// <summary>
    /// Timestamp (generated by the server, never by the professional's phone) of when they
    /// pressed "I'm on site". Only applies to the accepted professional.
    /// </summary>
    public DateTime? ArrivalConfirmedAt { get; set; }

    public ServiceProfessionalStatus Status { get; set; } = ServiceProfessionalStatus.UnderNegotiation;

    // Navigation properties
    public Professional Professional { get; set; } = null!;
    public Service Service { get; set; } = null!;
}
